environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C ..\\appveyor\\run_with_compiler.cmd"

  matrix:

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: http://www.appveyor.com/docs/installed-software#python
    
    fast_finish: true

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.9" # currently 2.7.9
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.3" # currently 3.4.3
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.9" # currently 2.7.9
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.3" # currently 3.4.3
      PYTHON_ARCH: "64"

    # Python versions not installed by default...
    
    - PYTHON: "C:\\Python266"
      PYTHON_VERSION: "2.6.6"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python266-x64"
      PYTHON_VERSION: "2.6.6"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"    

branches:
    only:
        - master
    
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell appveyor\\install.ps1"

build: off

cache:

  - wheelhouse -> appveyor\dependencyversions.txt

test_script:
    #- "%WITH_COMPILER% %PYTHON%/python setup.py test"
  - echo "Skipped"

after_test:
  - cd accelerate
  - "ECHO %WITH_COMPILER% %PYTHON%/python.exe setup.py bdist_wheel"
  - "%WITH_COMPILER% %PYTHON%/python.exe setup.py bdist_wheel"
  - cd ..

artifacts:
  - path: accelerate\dist\*
    name: dist
  
  - path: wheelhouse\*.whl
    name: numpy

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
